### ISSUE TITLE
Payment detection server response not compatible with client (broken)

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#171]

**Comment by Klakurka** [comment]
Ok so this is due to the API pulling data from the DB and the DB not getting updated without manually logging in each time.

**Comment by chedieck** [comment]
Is this solved with #313 ?

**Comment by Klakurka** [comment]
I think this is still not working. At least I have questions about it in https://github.com/PayButton/paybutton-server/pull/315.

**Comment by chedieck** [comment]
@Klakurka is this solved now?

**Comment by Klakurka** [comment]
The client polling is still broken so we'll need to get that fixed up first before closing this one.

https://github.com/PayButton/paybutton/issues/195

**Comment by Klakurka** [comment]
This one fails:

> http://localhost:3000/address/transactions/bitcoincash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7q9ayphulp

This one works fine:

> http://localhost:3000/address/balance/bitcoincash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7q9ayphulp

**Comment by vorg-code** [comment]
Before we were answering an error when a new wallet (that wasn't in our database) got sent through this endpoint /address/transactions, so, frontend paybutton just got lots of silent errors in the network tab and no transaction would ever be recognized there.

Now if an address that we don't have hits this endpoint, we add it to our database, fetch the transactions from the node and then return the list of transactions. If this is an address with a boatload of transactions, this endpoint could take 1 minute to answer the first time and some seconds in each request, but it should not fail anymore.

Unit test was also changed to the new situation.
